# this file is autogenerated by .github/workflows/update.yml
{
  x86_64-linux.database = builtins.fetchurl {
    url = "https://github.com/R-VdP/nix-index-database/releases/download/2022-12-26-145441/index-x86_64-linux";
    sha256 = "08yz1fzlgxr9hzibd8dj1qfv463bw88p3hljlhnmykhhaicw8pvd";
  };
  aarch64-linux.database = builtins.fetchurl {
    url = "https://github.com/R-VdP/nix-index-database/releases/download/2022-12-26-145441/index-aarch64-linux";
    sha256 = "0ibc0q75pfgznhw8miy11h1p5pnwg91qbx8m8x2ca8s5am6xf28w";
  };
  x86_64-darwin.database = builtins.fetchurl {
    url = "https://github.com/R-VdP/nix-index-database/releases/download/2022-12-26-145441/index-x86_64-darwin";
    sha256 = "0vpjm3mf8wdds1q4dk8wbbn04f3wbpzxyip0045db6a5gglhnxyz";
   };
  aarch64-darwin.database = builtins.fetchurl {
    url = "https://github.com/R-VdP/nix-index-database/releases/download/2022-12-26-145441/index-aarch64-darwin";
    sha256 = "05fr2wfffl99gkk3sal84jb80w6j6jmfrh25j5gxim3gsd5k22sx";
  };
}
